version: '3.6'
services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
  app:
    build:
      context: backend/app
    depends_on:
      - graphql-engine
    restart: always
    env_file:
      - .env
  admin:
    build:
      context: backend/admin
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/admin" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  graphql-engine:
    image: hasura/graphql-engine:v2.2.0.cli-migrations-v3
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend/migrations:/hasura-migrations/
      - ./backend/metadata:/hasura-metadata/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthz" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  nginx:
    image: nginx:1.21-alpine
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/common.conf:/etc/nginx/common.conf
      - ./nginx/common_location.conf:/etc/nginx/common_location.conf
    depends_on:
      - admin
      - graphql-engine
volumes:
  db_data: