services:
  hls_aripi-spre-cer:
    build:
      context: .
    command: ffmpeg -y -i 'https://mobile.stream.aripisprecer.ro/radio.mp3;' -c:a:0
      libfdk_aac -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async
      1 -ac 2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/aripi-spre-cer:/data
  hls_aripi-spre-cer-instrumental:
    build:
      context: .
    command: ffmpeg -y -i 'https://instrumental.stream.aripisprecer.ro/radio.mp3;'
      -c:a:0 libfdk_aac -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1
      160k -async 1 -ac 2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time
      6 -hls_list_size 5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map
      'a:0,name:normal,default:yes a:1,name:high' -hls_flags delete_segments+omit_endlist
      -hls_start_number_source epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/aripi-spre-cer-instrumental:/data
  hls_aripi-spre-cer-international:
    build:
      context: .
    command: ffmpeg -y -i 'https://international.stream.aripisprecer.ro/radio.mp3;'
      -c:a:0 libfdk_aac -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1
      160k -async 1 -ac 2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time
      6 -hls_list_size 5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map
      'a:0,name:normal,default:yes a:1,name:high' -hls_flags delete_segments+omit_endlist
      -hls_start_number_source epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/aripi-spre-cer-international:/data
  hls_aripi-spre-cer-popular:
    build:
      context: .
    command: ffmpeg -y -i 'https://popular.stream.aripisprecer.ro/radio.mp3;' -c:a:0
      libfdk_aac -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async
      1 -ac 2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/aripi-spre-cer-popular:/data
  hls_aripi-spre-cer-predici:
    build:
      context: .
    command: ffmpeg -y -i 'https://predici.stream.aripisprecer.ro/radio.mp3;' -c:a:0
      libfdk_aac -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async
      1 -ac 2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/aripi-spre-cer-predici:/data
  hls_aripi-spre-cer-worship:
    build:
      context: .
    command: ffmpeg -y -i 'https://worship.stream.aripisprecer.ro/radio.mp3;' -c:a:0
      libfdk_aac -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async
      1 -ac 2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/aripi-spre-cer-worship:/data
  hls_nginx:
    image: nginx:1.21-alpine
    ports:
    - 80:80
    restart: on-failure
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - /tmp/data:/tmp/data
  hls_radio-alt-fm-arad:
    build:
      context: .
    command: ffmpeg -y -i 'http://asculta.radiocnm.ro:8002/live' -c:a:0 libfdk_aac
      -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac
      2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-alt-fm-arad:/data
  hls_radio-armonia:
    build:
      context: .
    command: ffmpeg -y -i 'http://video.bluespot.ro:8001/listen.mp3' -c:a:0 libfdk_aac
      -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac
      2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-armonia:/data
  hls_radio-biblia-online:
    build:
      context: .
    command: ffmpeg -y -i 'http://209.95.50.189:8006/' -c:a:0 libfdk_aac -profile:a:0
      aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac 2 -r 44100 -map
      0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size 5 -hls_delete_threshold
      10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes a:1,name:high'
      -hls_flags delete_segments+omit_endlist -hls_start_number_source epoch -master_pl_publish_rate
      2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-biblia-online:/data
  hls_radio-biruitor:
    build:
      context: .
    command: ffmpeg -y -i 'https://cast1.asurahosting.com/proxy/valer/stream' -c:a:0
      libfdk_aac -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async
      1 -ac 2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-biruitor:/data
  hls_radio-ciresarii:
    build:
      context: .
    command: ffmpeg -y -i 'https://s3.radio.co/s6c0a773ad/listen' -c:a:0 libfdk_aac
      -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac
      2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-ciresarii:/data
  hls_radio-de-cuvant:
    build:
      context: .
    command: ffmpeg -y -i 'https://streamer.radio.co/sb94ce6fe2/listen' -c:a:0 libfdk_aac
      -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac
      2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-de-cuvant:/data
  hls_radio-ekklesia:
    build:
      context: .
    command: ffmpeg -y -i 'http://asculta.radioekklesia.com:8005/stream' -c:a:0 libfdk_aac
      -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac
      2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-ekklesia:/data
  hls_radio-elim-air:
    build:
      context: .
    command: ffmpeg -y -i 'http://91.213.11.102:8011/stream' -c:a:0 libfdk_aac -profile:a:0
      aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac 2 -r 44100 -map
      0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size 5 -hls_delete_threshold
      10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes a:1,name:high'
      -hls_flags delete_segments+omit_endlist -hls_start_number_source epoch -master_pl_publish_rate
      2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-elim-air:/data
  hls_radio-elim-kids:
    build:
      context: .
    command: ffmpeg -y -i 'http://91.213.11.102:8007/stream' -c:a:0 libfdk_aac -profile:a:0
      aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac 2 -r 44100 -map
      0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size 5 -hls_delete_threshold
      10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes a:1,name:high'
      -hls_flags delete_segments+omit_endlist -hls_start_number_source epoch -master_pl_publish_rate
      2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-elim-kids:/data
  hls_radio-elim-plus:
    build:
      context: .
    command: ffmpeg -y -i 'http://91.213.11.102:8003/stream' -c:a:0 libfdk_aac -profile:a:0
      aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac 2 -r 44100 -map
      0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size 5 -hls_delete_threshold
      10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes a:1,name:high'
      -hls_flags delete_segments+omit_endlist -hls_start_number_source epoch -master_pl_publish_rate
      2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-elim-plus:/data
  hls_radio-filadelfia:
    build:
      context: .
    command: ffmpeg -y -i 'https://asculta.radiofiladelfia.ro:8000/;' -c:a:0 libfdk_aac
      -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac
      2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-filadelfia:/data
  hls_radio-gosen:
    build:
      context: .
    command: ffmpeg -y -i 'https://sp.totalstreaming.net/8125/stream' -c:a:0 libfdk_aac
      -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac
      2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-gosen:/data
  hls_radio-iubire-fara-margini:
    build:
      context: .
    command: ffmpeg -y -i 'http://ssl.omegahost.ro:7043/stream' -c:a:0 libfdk_aac
      -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac
      2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-iubire-fara-margini:/data
  hls_radio-levi:
    build:
      context: .
    command: ffmpeg -y -i 'https://audio-radioleviro.bisericilive.com/radioleviro.mp3'
      -c:a:0 libfdk_aac -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1
      160k -async 1 -ac 2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time
      6 -hls_list_size 5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map
      'a:0,name:normal,default:yes a:1,name:high' -hls_flags delete_segments+omit_endlist
      -hls_start_number_source epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-levi:/data
  hls_radio-micul-samaritean:
    build:
      context: .
    command: ffmpeg -y -i 'https://s5.radio.co/sfff7b7e97/listen' -c:a:0 libfdk_aac
      -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac
      2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-micul-samaritean:/data
  hls_radio-moody-chicago:
    build:
      context: .
    command: ffmpeg -y -i 'https://primary.moodyradiostream.org/wrmb-high.aac' -c:a:0
      libfdk_aac -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async
      1 -ac 2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-moody-chicago:/data
  hls_radio-o-noua-sansa:
    build:
      context: .
    command: ffmpeg -y -i 'https://securestreams5.autopo.st:1951/;?type=http&nocache=15'
      -c:a:0 libfdk_aac -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1
      160k -async 1 -ac 2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time
      6 -hls_list_size 5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map
      'a:0,name:normal,default:yes a:1,name:high' -hls_flags delete_segments+omit_endlist
      -hls_start_number_source epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-o-noua-sansa:/data
  hls_radio-old-christian-radio:
    build:
      context: .
    command: ffmpeg -y -i 'https://stream.radio.co/sf2c714555/listen' -c:a:0 libfdk_aac
      -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac
      2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-old-christian-radio:/data
  hls_radio-philadelphia-mansue:
    build:
      context: .
    command: ffmpeg -y -i 'http://94.130.106.91/radio/8000/radio.mp3' -c:a:0 libfdk_aac
      -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac
      2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-philadelphia-mansue:/data
  hls_radio-vocea-evangheliei-bucuresti:
    build:
      context: .
    command: ffmpeg -y -i 'https://lb01.bpstream.com:8618/stream' -c:a:0 libfdk_aac
      -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async 1 -ac
      2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-vocea-evangheliei-bucuresti:/data
  hls_radio-vocea-evangheliei-cluj:
    build:
      context: .
    command: ffmpeg -y -i 'https://s23.myradiostream.com/:18366/listen.mp3' -c:a:0
      libfdk_aac -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async
      1 -ac 2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-vocea-evangheliei-cluj:/data
  hls_radio-vocea-evangheliei-constanta:
    build:
      context: .
    command: ffmpeg -y -i 'https://audio-rvectro.bisericilive.com/rvectro.mp3' -c:a:0
      libfdk_aac -profile:a:0 aac_he_v2 -b:a:0 64k -c:a:1 libfdk_aac -b:a:1 160k -async
      1 -ac 2 -r 44100 -map 0:a:0 -map 0:a:0 -f hls -hls_init_time 2 -hls_time 6 -hls_list_size
      5 -hls_delete_threshold 10 -master_pl_name index.m3u8 -var_stream_map 'a:0,name:normal,default:yes
      a:1,name:high' -hls_flags delete_segments+omit_endlist -hls_start_number_source
      epoch -master_pl_publish_rate 2 -sc_threshold 0 /data/%v/index.m3u8
    restart: on-failure
    volumes:
    - /tmp/data/hls/radio-vocea-evangheliei-constanta:/data
version: '3.3'
